apiVersion: apps/v1
kind: Deployment
metadata:
  name: billforge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billforge
  template:
    metadata:
      labels:
        app: billforge
    spec:
      containers:
      - name: billforge
        image: yourdockerhub/billforge:latest
        ports:
        - containerPort: 5000
