version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: docker build -t yourdockerhub/billforge .
      - run: echo "Mock docker push && kubectl apply -f k8s/"

workflows:
  build_and_deploy:
    jobs:
      - build
