version: 2.1

jobs:
  build_and_push:
    machine: true  # ← This gives access to Docker daemon
    steps:
      - checkout

      - run:
          name: Log in to DockerHub
          command: |
            echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Build Docker image
          command: docker build -t jayvardhannegi/billforge:latest .

      - run:
          name: Push Docker image
          command: docker push jayvardhannegi/billforge:latest

      - run:
          name: Mock Kubernetes Deploy
          command: echo "kubectl apply -f k8s/"

workflows:
  build-deploy:
    jobs:
      - build_and_push
