apiVersion: apps/v1
kind: Deployment
metadata:
  name: billforge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billforge
  template:
    metadata:
      labels:
        app: billforge
    spec:
      containers:
      - name: billforge
        image: 605671347906.dkr.ecr.ap-south-1.amazonaws.com/billforge:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: billforge-service
spec:
  type: LoadBalancer
  selector:
    app: billforge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
